name: nutri_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.0

  # --- PACOTES ATUALIZADOS PARA O FLUTTER WEB 3.44+ ---
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.0
  google_fonts: ^6.2.0
  brasil_fields: ^1.14.0
  image_picker: ^1.1.2
  google_generative_ai: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: FunkyGlitz
      fonts:
        - asset: assets/fonts/funky_glitz.ttf

    - family: BrightMiracle
      fonts:
        - asset: assets/fonts/bright_miracle.ttf

    - family: NicePaper
      fonts:
        - asset: assets/fonts/nice_paper.ttf