// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA50aZfXcCK0lWEXpHe_XbIr8g3d5vwPho',
    appId: '1:263275442085:web:ee5bb306ce5e50019fc24c',
    messagingSenderId: '263275442085',
    projectId: 'nutri-app-6f73b',
    authDomain: 'nutri-app-6f73b.firebaseapp.com',
    storageBucket: 'nutri-app-6f73b.firebasestorage.app',
    measurementId: 'G-4ZES604YQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7jtNGPlcyqt_CTosis8Wsyfk_ZaSnO7Q',
    appId: '1:263275442085:android:b188fd4ddb5b62629fc24c',
    messagingSenderId: '263275442085',
    projectId: 'nutri-app-6f73b',
    storageBucket: 'nutri-app-6f73b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZBDZhDiNWI8wbby4ARZNw5-U7dVJL4s0',
    appId: '1:263275442085:ios:3098baef2433fc6f9fc24c',
    messagingSenderId: '263275442085',
    projectId: 'nutri-app-6f73b',
    storageBucket: 'nutri-app-6f73b.firebasestorage.app',
    iosBundleId: 'com.example.nutriApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZBDZhDiNWI8wbby4ARZNw5-U7dVJL4s0',
    appId: '1:263275442085:ios:3098baef2433fc6f9fc24c',
    messagingSenderId: '263275442085',
    projectId: 'nutri-app-6f73b',
    storageBucket: 'nutri-app-6f73b.firebasestorage.app',
    iosBundleId: 'com.example.nutriApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA50aZfXcCK0lWEXpHe_XbIr8g3d5vwPho',
    appId: '1:263275442085:web:39a87b7ad6d7e2a49fc24c',
    messagingSenderId: '263275442085',
    projectId: 'nutri-app-6f73b',
    authDomain: 'nutri-app-6f73b.firebaseapp.com',
    storageBucket: 'nutri-app-6f73b.firebasestorage.app',
    measurementId: 'G-08XQ57N4YP',
  );
}
